name: Build & Deploy Demo Site

on:
  push:
    branches:
      - '**'  # trigger on any branch push

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: "npm"

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Build library
      - name: Build library
        run: npm run build

      # 5. Build demo
      - name: Build demo
        run: npm run build:demo

      # 6. Deploy ./site/dist to GitHub Pages
      - name: Deploy to GitHub Pages
        if: github.ref_name == github.event.repository.default_branch
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site/dist
          # use the branch that triggered the workflow
          publish_branch: gh-pages
          force_orphan: true
          enable_jekyll: false
